### PR TITLE
Merge hl into master

### PR DESCRIPTION
**Pull request by ajgdls**
Hi @timcnicholls I've decided to create this PR now so we have visibility.  Currently I have fixed the adapter to work with the base detector class for testing but I haven't yet added the unit tests for the new classes and so this fails on coverage.
If you are happy to leave this open for a little while I will get those tests added.

### CODE REVIEW

**Comment by timcnicholls** [comment]
Hi @ajgdls that's fine. Do you want any immediate feedback?

**Comment by ajgdls** [comment]
Yes feel free but I can not promise any immediate response ;)

**Comment by GDYendell** [comment]
I would like to update this to use the dictionary based udp config parsing before it is merged.

**Comment by ajgdls** [comment]
I'm also writing some tests for hl_detector.  I'm finally going to get those started today...

**Comment by GDYendell** [comment]
@ajgdls the setup.py has been updated in dls-master. Does that need merging too?

**Comment by GDYendell** [comment]
I have tested the latest commit for UDP config updates for both modes. They both get as far as parsing the config file and then setting the fe parameters fails. I have tested the direct FEM mode produces good images on the i07 lab system, but I don't have a switch system to test.

**Comment by ajgdls** [comment]
Hi @GDYendell you have force pushed this branch.  What is the implication for my version of the branch with the tests?  Do I just fetch?

**Comment by GDYendell** [comment]
You need to take out 040958c. That is reverting some of the  changes I made in 55a89a2.

**Comment by ajgdls** [comment]
@GDYendell please explain.  I have re-based and took your changes, so how have I managed to revert changes?

**Pull request merged**
