### PR TITLE
Implemented parameter tree for Excalibur.

### PR DESCRIPTION
**Pull request by ajgdls**
Major rework of Excalibur detector HL control:
1) Added a control simulator to allow execution and simple tests without real hardware
2) Removed all custom Excalibur parameters and replaced with a ParameterTree implementation
3) Removed hard-coded strings and replaced with a series of class constants
4) Removed duplicate code and ensure all communications pass through the same methods for easier tracking of failures and consistent error message reporting

### CODE REVIEW

**Comment by ajgdls** [comment]
I'm aware the CI tests have failed.  Looking at those now and will push fix

**Comment by GDYendell** [comment]
Do we want this to go in to the next release along with 24 bit mode?

**Comment by timcnicholls** [comment]
@GDYendell If @ajgdls is happy, I don't see why it shouldn't go in.

We're just completing testing of 24-bit mode on the lab 29 1M detector so I'll discuss with Alan today.

**Comment by GDYendell** [comment]
I have created a branch dls-changes with all the changes we have built up on dls-master that should have been merged to master. I have replaced this branch with the first 3 commits of that branch, as that is what we are actively using at dls.

**Review by ajgdls — COMMENTED** [review]
We shouldn't sit on this one for years - hopefully as it's currently in use at DLS and doesn't impact much on the main detector class it is straight-forward to approve.
I would approve it myself but I can't as it is my own PR!  @GDYendell you can approve it even though you pushed the branch.

**Review by GDYendell — APPROVED** [review]

**Comment by GDYendell** [comment]
I do also have another set of changes to merge to get master in line with dls-master, but I didn't want to do them all in one lump. These are here: https://github.com/dls-controls/excalibur-detector/tree/dls-changes

**Review by timcnicholls — APPROVED** [review]

**Pull request merged**
