### PR TITLE
Add EXCALIBUR frame producer script

### PR DESCRIPTION
**Pull request by timcnicholls**
This python script can load EXCALIBUR packet capture (PCAP) files saved with tcpdump and play them back over a UDP socket to allow testing of the ODIN data path.

### CODE REVIEW

**Comment by timcnicholls** [comment]
@ajgdls Please can you review this - note also I've moved the producer script over from control to data as discussed last week.

**Comment by ajgdls** [comment]
I notice you've included my fudge commit, are you happy with that?

**Comment by timcnicholls** [comment]
Didn't want to clobber it! I could put an option in around it so we can still preserve full speed?

**Comment by timcnicholls** [comment]
@ajgdls Added a CLI option pkt_gap for your fudge now.

**Pull request merged**
